actyx/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.views.generic.base import RedirectView

urlpatterns = [
        # Root URL
        url(r'^$', RedirectView.as_view(
                pattern_name='challenge1:index',
                permanent=False,
                query_string=False,
                )),

        # Apps
        url(r'^backend/', include(admin.site.urls)),
        url(
                r'^challenge1/',
                include('actyx1.urls', namespace='challenge1'),
                )
]

actyx1/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        # Root URL
        url(r'^$', views.index, name='index'),

        # See all machines
        url(r'^machines/', views.IndexView.as_view(), name='machines'),
        # Fetch data from the Actyx API
        url(r'^fetch/(\w*)', views.fetch, name='fetch_api'),
        # API
        url(r'^api/stream/(\w*)', views.api_stream, name='API_stream'),


        url(r'^test/', views.test, name='TST'),
        ]

actyx1/models.py
import datetime
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone


class Machine(models.Model):
        """A machine tracked by the application"""
        uuid = models.CharField(
                        'Machine UUID',
                        primary_key=True,
                        max_length=37,  # According to the default format
                        )
        name = models.CharField('Machine name', max_length=500)
        machinetype = models.CharField('Machine type', max_length=100)
        location_x = models.FloatField(null=True)
        location_y = models.FloatField(null=True)

        def location(self):
                t = (self.location_x, self.location_y)
                if t == (None, None):
                        return None
                else:
                        return t
        location.short_description = 'The coordinates for the machine'

        def __str__(self):
                return 'mUUID: %s' % self.uuid


class MachinePark(models.Model):
        """A set of machines"""
        machines = models.ManyToManyField(Machine)

        def __str__(self):
                if self.id is None:
                        return 'MachinePark being built'
                return 'MachinePark %d' % self.id

actyx1/views.py
import time
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.http import StreamingHttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import *
from actyx.api import APIActyx, APIUnavailableException
import logging
logger = logging.getLogger(__name__)


def index(request):
        context = {
                        'title': 'Hello, World',
                        }
        return render(request, 'actyx1/index.django.html', context)


class IndexView(generic.ListView):
        model = Machine
        template_name = 'actyx1/machines.django.html'
        context_object_name = 'machines'
        ordering = 'name'

        def get_context_data(self, **kwargs):
                # Call the super function
                context = super(self.__class__, self).get_context_data(**kwargs)
                context['title'] = 'All Machines'
                return context


def fetch(request, selector):
        """Fetch all data from the Actyx API"""
        # return HttpResponseRedirect(reverse('challenge1:machines'))
        response = StreamingHttpResponse(fetch_generator(selector))
        return response


def fetch_generator(selector):
        yield '<h1>Actyx API Fetch</h1>'
        do = selector == 'ALL'
        if selector == 'NONE':
                raise Http404('Do nothing!')
        try:
                mp = MachinePark.objects.get(pk=1)
                yield '<h2>MachinePark Retrieved</h2>'
        except MachinePark.DoesNotExist as e:
                # Create the MachinePark
                mp = MachinePark.objects.create()
                yield '<h2>MachinePark Created</h2>'
        # Delete all existing machines
        for m in Machine.objects.all():
                m.delete()
        yield '<h2>Old machines deleted</h2>'
        api = APIActyx()
        yield '<h2>API object created</h2>'
        uuid_list = []
        try:
                uuid_list = api.streamMachinesUUID()
        except APIUnavailableException as e:
                yield '<b style="color:red;"><i>ERROR: %s</i></b>' % e
        yield '<ul>'
        for uuid in uuid_list:
                yield '<li>Machine UUID: <b>%s</b><br>' % uuid
                try:
                        metadata = api.getMachineData(uuid)
                        # Create a new Machine
                        m = Machine()
                        m.uuid = uuid
                        m.name = metadata['name']
                        m.machinetype = metadata['type']
                        location = [float(n) for n in metadata['location'].split(',')]
                        m.location_x = location[0]
                        m.location_y = location[1]
                        m.save()
                        mp.machines.add(m)
                        yield '<i>Done!</i>'
                except Exception as e:
                        yield '<b style="color:red;"><i>ERROR: %s</i></b>' % e
                finally:
                        yield '</li>'
        mp.save()
        yield '</ul>'
        yield '<h1>Done!</h1>'
        yield 'Get back <a href="/">Home</a>'


def api_stream(request, argument=None):
        """Fetch all data from the Actyx API"""
        response = StreamingHttpResponse(api_stream_generator(request, argument))
        response['Content-Type'] = 'application/json'
        return response


def api_stream_generator(reques, argument=None):
        """Stream the real-time current data as JSON objects"""
        api = APIActyx()
        try:
                uuid_list = api.getMachinesUUID()
                while True:
                        now = None
                        return_data = {'data': {}, 'warnings': {}}
                        for uuid in uuid_list:
                                metadata = api.getMachineData(uuid)
                                current = metadata['current']
                                current_alert = metadata['current_alert']
                                current_pct = round(100 * current / current_alert, 2)
                                working = metadata['state'] == 'working'
                                timestamp = metadata['timestamp']
                                if now is None:
                                        now = timestamp
                                else:  # Store the oldest updated timestamp
                                        if timestamp < now:
                                                now = timestamp
                                if working and current > current_alert:
                                        # It's over the maximum amount, warn the user
                                        return_data['warnings'][uuid] = -1 #TODO: rolling average of the last 5min
                                return_data['data'][uuid] = [working, current_pct, current]
                        return_data['last_updated'] = APIActyx.format_timestamp(now or time.time())
                        if len(return_data['data']) > 0:
                                yield json.dumps(return_data)
                                # This hack makes sure the servers flush their caches
                                # Use ESC (ASCII 033) so that it doesn't collide with non-binary data
                                yield '\033' * 1024
        except APIUnavailableException as e:
                yield json.dumps({'error': 'The API is not available at this moment'})
                # This hack makes sure the servers flush their caches
                # Use ESC (ASCII 033) so that it doesn't collide with non-binary data
                yield '\033' * 1024


def test(request):
        context = {
                        'title': 'API Test - Stream data',
                        'arr': range(1, 100),
                        }
        return render(request, 'actyx1/test_api.django.html', context)

actyx1/templates/actyx1/base/base.django.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- HTML5 -->
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'actyx1/base.css' %}"></link>
		{% block head %}
			<title>{% if title %}{{ title }} | {% endif %}Actyx Challenge 1</title>
		{% endblock head %}
	</head>
	<body>
		<div id="topbar">
			<div class="topbar-item">
				<a href="{% url 'challenge1:index' %}">
					<img src="{% static 'actyx/logo.png' %}" alt="Actyx Logo">
				</a>
			</div>
			<div class="topbar-item">
				{% block title %}
					<p class="title">{{ title }}</p>
				{% endblock title %}
			</div>
			<div class="topbar-item">
				{% block extra-links %}
				{% endblock extra-links %}
				<a href="{% url 'challenge1:machines' %}">All Machines</a>
			</div>
		</div>
		<div id="content">
			{% block content %}
				<p>Something's wrong, get to a safe place <a href="{% url 'challenge1:index' %}">HERE</a></p>
			{% endblock content %}
		</div>
	</body>
</html>

actyx1/templates/actyx1/index.django.html
{% extends "actyx1/base/base.django.html" %}

{% block content %}
	<h1>{{ title }}</h1>
	<a href="{% url 'challenge1:fetch_api' 'ALL' %}">Fetch all data</a>
	<p>List all machines</p>
	<a href="{% url 'challenge1:machines' %}">All Machines</a>
{% endblock %}

actyx1/templates/actyx1/machines.django.html
{% extends 'actyx1/base/base.django.html' %}
{% load staticfiles %}

{% block head %}
	{{ block.super }}
	<link rel="api-endpoint" href="{% url 'challenge1:API_stream' '' %}" title="Data API Endpoint" id="link-api-endpoint"></link>
	<link rel="stylesheet" type="text/css" href="{% static 'actyx1/machines.css' %}"></link>
	<script async type="text/javascript" src="{% static 'actyx1/machines.js' %}"></script>
{% endblock head %}

{% block title %}
	<p id="p_updating"></p>
	<p id="p_updated-date" class="hidden">
		<span>Last Update</span>
		<span id="updated-date" title="Stop Updating"></span>
		<span id="updated-stop" class="hidden">Stopped Updating</span>
	</p>
	<button id="retry" onclick="window.location.reload()" class="hidden">Reload Page</button>
{% endblock title %}

{% block content %}
	<h2 id="p_warnings"class="hidden">Warnings</h2>
	<ul id="list-warnings" class="hidden"></ul>
	<h2>Machines</h2>
	<ul id="machines">
		{% for m in machines %}
			<li id="uuid_{{ m.uuid }}" class="machine" title="{{ m.uuid }}">
				<meter value=0 min=0 max=100 high=80></meter>
				{% if m.location %}
					<span class="location"><b>Location: </b><span>{{ m.location }}</span></span>
				{% endif %}
				<span class="name">{{ m.name }}</span>
				<span class="type">{{ m.machinetype }}</span>
			</li>
		{% endfor %}
	</ul>
{% endblock content %}

actyx1/templates/actyx1/test_api.django.html
{% extends 'actyx1/base/base.django.html' %}
{% load staticfiles %}

{% block head %}
	<link rel="api-endpoint" href="{% url 'challenge1:API_stream' %}" title="Data API Endpoint" id="link-api-endpoint">
	<link rel="stylesheet" type="text/css" href="{% static 'actyx1/tstapi.css' %}"></link>
{% endblock head %}

{% block content %}
	<h2>Warnings</h2>
	<ul class="list warnings" id="list-warnings"></ul>
	<h2>Title</h2>
	<ul class="list" id="list">
		{% for number in arr %}
			<li id="li-{{ number }}">{{ number }}</li>
		{% endfor %}
	</ul>
	<h2>END</h2>

	<script type="text/javascript" charset="utf-8" src={% static 'actyx1/tstapi-stream.js' %}></script>
{% endblock content %}